In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [9]:
df = pd.read_csv("E:\Datasets\session 24\iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [12]:
df = df.drop('Id',axis=1)

In [13]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()

In [15]:
x=df.iloc[:,:4]

In [16]:
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [17]:
y=df.iloc[:,4]

In [18]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [20]:
y= encoder.fit_transform(y)

In [21]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=5)


In [22]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
nb= GaussianNB()

In [25]:
nb.fit(x_train,y_train)

GaussianNB()

In [27]:
y_pred = nb.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9

In [40]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [41]:
x_train

array([[-0.88140924,  0.72750289, -1.23547394, -1.26527703],
       [-0.40389633, -1.69139841,  0.17434798,  0.16834158],
       [-0.16513988, -1.03169805, -0.10761641, -0.22264531],
       [-0.52327456,  1.38720324, -1.23547394, -1.26527703],
       [ 1.38677706,  0.28770265,  0.56909811,  0.29867054],
       [-1.00078746,  0.50760277, -1.29186681, -1.26527703],
       [-1.00078746,  0.94740301, -1.17908106, -0.74396117],
       [ 2.22242464, -0.15209758,  1.35859839,  1.47163122],
       [-1.00078746,  0.94740301, -1.34825969, -1.13494806],
       [ 0.6705077 ,  0.28770265,  0.90745537,  1.47163122],
       [-0.04576165, -0.81179793,  0.79466962,  0.95031536],
       [-0.28451811, -1.25159817,  0.1179551 , -0.09231635],
       [-0.88140924,  0.94740301, -1.29186681, -1.13494806],
       [-0.88140924,  1.60710336, -1.17908106, -1.26527703],
       [ 0.78988593, -0.59189782,  0.51270524,  0.42899951],
       [ 0.43175125, -0.59189782,  0.62549099,  0.8199864 ],
       [ 0.07361657, -0.

In [42]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [43]:
x_train

array([[0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.58333333, 0.5       , 0.72881356, 0.91666667],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.52777778, 0.33333333, 0.6440678 , 0.70833333],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.66666667, 0.54166667,

In [44]:
x_test

array([[0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.16666667, 0.16666667, 0.38983051, 0.375     ],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.19444444, 0.41666667, 0.10169492, 0.04166667],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.77777778, 0.41666667, 0.83050847, 0.83333333],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.86111111, 0.33333333,

In [45]:
scaled_nb = GaussianNB()

In [46]:
scaled_nb.fit(x_train,y_train)

GaussianNB()

In [47]:
y_pred_scaled = scaled_nb.predict(x_test)

In [48]:
accuracy_score(y_test,y_pred_scaled)

0.9

## ##Conclusion

Clearly there is no change in accuracy of results before and after scaling.
The reason is that naive bayes simply calculates the probablity. So it doesnt make any difference.